### ISSUE TITLE
Sublime 3 Build 3127-3128 break Seti

### ISSUE THREAD

**Issue by louim** [ctf0/Seti_ST3#293]
Hey! Long time Seti user here. Thanks for the awesome work! Today Sublime released an update that broke Seti. It currently looks like this 😱 

<img width="1392" alt="capture d ecran 2017-04-12 a 22 33 28" src="https://cloud.githubusercontent.com/assets/923718/24987900/6e9a13b0-1fd0-11e7-83bc-4d0ded59609b.png">

**Comment by ctf0** [comment]
i presume u r using the dev build, i honestly want to wait till the next stable release but i will look into it.

**Comment by tuzemec** [comment]
There's a general change in the theme engine that's causing this.
More info here: https://www.sublimetext.com/3dev  Build 3127
And the updated engine docs: http://www.sublimetext.com/docs/3/themes.html

**Comment by wbond** [comment]
Just a heads up, the next stable release will likely be 3.0.

**Comment by wbond** [comment]
I am looking into these issues right now. There was one change that may have affected third-party themes (it was how the base theme rules were applied), however it should not have effects like this.

**Comment by wbond** [comment]
This should be resolved in the next dev build

**Comment by tuzemec** [comment]
@wbond Thanks a lot for the swift response!

**Comment by ctf0** [comment]
@louim i just tested it on Win and it seems fixed, do u still have this issue on ur machine ?

**Comment by louim** [comment]
Last update of Sublime fixed most of the bugs. Only thing looking broken right now it the arrows on the top left, they look really pixelated / blocky. And the hamburger menu on the top right is looking weird too.

**Comment by ctf0** [comment]
okay, will see about that

**Comment by ctf0** [comment]
@louim check the latest release notes regarding the arrow pixelization issue.
